# Generated by Django 4.2.2 on 2023-07-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stuff/'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
