# Generated by Django 4.2.2 on 2023-07-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0002_alter_stuff_photo_alter_stuff_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='categorie',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stuff',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
