# Generated by Django 4.2.2 on 2023-07-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0003_stuff_categorie_stuff_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuff',
            old_name='categorie',
            new_name='category',
        ),
    ]
